apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dp-prod
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dp-nginx
  name: dp-nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dp-nginx
    spec:
      containers:
      - image: deliverypartsru/dp-nginx
        name: dp-nginx
        ports:
        - containerPort: 8001
        resources: {}
        volumeMounts:
        - name: dp-data
          mountPath: /mnt/dp-data
        - name: dp-nginx-www
          mountPath: /etc/nginx/conf.d/www.conf
      restartPolicy: Always
      volumes:
      - name: dp-data
        persistentVolumeClaim:
          claimName: dp-data
      - name: dp-nginx-www
        configMap:
            name: dp-nginx-www
status: {}
