apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    traefik.backend: dp-nginx
    traefik.enable: "true"
    traefik.frontend.rule: Host:beta.delivery-parts.ru
    traefik.port: "8001"
    traefik.protocol: http
  creationTimestamp: null
  labels:
    io.kompose.service: dp-nginx
  name: dp-nginx
spec:
  ports:
  - name: "8001"
    port: 8001
    targetPort: 8001
  selector:
    io.kompose.service: dp-nginx
status:
  loadBalancer: {}
