apiVersion: v1
kind: Service
metadata:
  namespace: dp-prod
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dp-php
  name: dp-php
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    io.kompose.service: dp-php
status:
  loadBalancer: {}
