apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: dp-traefik
  name: dp-traefik
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    io.kompose.service: dp-traefik
status:
  loadBalancer: {}
