apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
    traefik.enable: "false"
  creationTimestamp: null
  labels:
    io.kompose.service: dp-traefik
  name: dp-traefik
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dp-traefik
    spec:
      containers:
      - image: dp-traefik
        name: dp-traefik
        ports:
        - containerPort: 8080
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /etc/traefik
          name: dp-traefik-claim0
        - mountPath: /var/run/docker.sock
          name: dp-traefik-claim1
      restartPolicy: Always
      volumes:
      - name: dp-traefik-claim0
        persistentVolumeClaim:
          claimName: dp-traefik-claim0
      - name: dp-traefik-claim1
        persistentVolumeClaim:
          claimName: dp-traefik-claim1
status: {}
