version: '3'

services:
    dp-nginx:
        image: deliverypartsru/dp-nginx
        container_name: dp-nginx
        restart: always
        ports:
            - "8001:8001"
        volumes:
            - ../dp-data/:/dp-data:rw
        links:
            - dp-php

    dp-php:
        image: deliverypartsru/dp-php
        container_name: dp-php
        restart: always
        ports: 
            - "9000:9000"
        networks:
            - dp-internal
        labels:
            - "traefik.enable=false"            

    dp-worker:
        image: deliverypartsru/dp-worker
        container_name: dp-worker
        restart: always
        ports:
            - "9001:9001"