apiVersion: v1
kind: Service
metadata:
  namespace: dp-prod
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dp-worker
  name: dp-worker
spec:
  ports:
  - name: "9001"
    port: 9001
    targetPort: 9001
  selector:
    io.kompose.service: dp-worker
status:
  loadBalancer: {}
