version: '3'

networks:
    dp-proxy:
        external: true
    dp-internal:
        external: false

services:
    dp-nginx:
        image: deliverypartsru/dp-nginx:1.3.20
        container_name: dp-nginx
        restart: always
        ports:
            - "8001:8001"
        volumes:
            - ../dp-data/etc/nginx/conf.d:/etc/nginx/conf.d
            - ../dp-data/var/www:/var/www:rw
            - ../dp-data/var/log/nginx:/var/log/nginx:rw
        links:
            - dp-php
        networks:
            - dp-internal
            - dp-proxy
        labels:
            - "traefik.enable=true"
            - "traefik.backend=dp-nginx"
            - "traefik.frontend.rule=Host:beta.delivery-parts.ru"
            - "traefik.port=8001"
            - "traefik.protocol=http"

    dp-php:
        image: deliverypartsru/dp-php:1.3.20
        container_name: dp-php
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ../dp-data/var/www:/var/www:rw
            - ../dp-data/var/log/php-fpm/dp-php:/var/log:rw
        networks:
            - dp-internal
        labels:
            - "traefik.enable=false"

    dp-worker:
        image: deliverypartsru/dp-worker:1.3.20
        container_name: dp-worker
        restart: always
        ports:
            - "9001:9001"
        volumes:
            - ../dp-data/var/www:/var/www:rw
            - ../dp-data/var/log/supervisor:/var/log/supervisor:rw
            - ../dp-data/etc/supervisor:/etc/supervisor
        networks:
            - dp-internal
        labels:
            - "traefik.enable=false"

    dp-traefik:
        image: deliverypartsru/dp-traefik:1.3.20
        container_name: dp-traefik
        restart: always
        ports:
            - "8080:8080"
            - "80:80"
            - "443:443"
        volumes:
            - ../dp-data/etc/traefik:/etc/traefik:rw
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - dp-internal
            - dp-proxy
        labels:
            - "traefik.enable=false"
