kind: PersistentVolume
apiVersion: v1 
metadata:
    name: dp-data
    namespace: dp-prod
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 2Gi
    accessModes:
        - ReadWriteMany
