apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dp-prod-nginx
  namespace: dp-prod
spec:
  rules:
  - host: beta.delivery-parts.ru
    http:
      paths:
      - backend:
          serviceName: dp-nginx
          servicePort: 8001
