apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dp-supervisor-wm
  namespace: dp-prod
spec:
  rules:
  - host: beta.delivery-parts.ru
    http:
      paths:
      - backend:
          serviceName: dp-worker
          servicePort: 9001
