apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dp-prod
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dp-worker
  name: dp-worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dp-worker
    spec:
      containers:
      - image: deliverypartsru/dp-worker:1.3.20
        name: dp-worker
        ports:
        - containerPort: 9001
        resources: {}
        volumeMounts:
        - mountPath: /mnt/dp-data
          name: dp-data
      restartPolicy: Always
      volumes:
      - name: dp-data
        persistentVolumeClaim:
          claimName: dp-data
status: {}
