apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dp-prod
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: dp-workspace
  name: dp-workspace
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: dp-workspace
    spec:
      containers:
      - image: deliverypartsru/dp-workspace:latest
        name: dp-workspace
        resources: {}
        volumeMounts:
        - name: dp-data
          mountPath: /mnt/dp-data

      restartPolicy: Always
      volumes:
      - name: dp-data
        persistentVolumeClaim:
          claimName: dp-data
status: {}
