version: '3'

networks:
    dp-proxy:
        external: true
    dp-internal:
        external: false

services:
    dp-nginx:
        build: ./images/nginx
        container_name: dp-nginx
        restart: always
        image: dp-nginx
        ports:
            - "8001:8001"
        volumes:
            - ../dp-data/etc/nginx/conf.d:/etc/nginx/conf.d
            - ../dp-data/var/www:/var/www:rw
            - ../dp-data/var/log/nginx:/var/log/nginx:rw
        links:
            - dp-php
        networks:
            - dp-internal
            - dp-proxy
        labels:
            - "traefik.enable=true"
            - "traefik.backend=dp-nginx"
            - "traefik.frontend.rule=Host:beta.delivery-parts.ru"
            - "traefik.port=8001"
            - "traefik.protocol=http"

    dp-php:
        build: ./images/php-fpm
        container_name: dp-php
        image: dp-php
        restart: always
        ports:
            - "9000:9000"
        volumes:
            - ../dp-data/var/www:/var/www:rw
            - ../dp-data/var/log/php-fpm/dp-php:/var/log:rw
        networks:
            - dp-internal
        labels:
            - "traefik.enable=false"

    dp-worker:
        build: ./images/worker
        container_name: dp-worker
        restart: always
        image: dp-worker
        ports:
            - "9001:9001"
        volumes:
            - ../dp-data/var/www:/var/www:rw
            - ../dp-data/var/log/supervisor:/var/log/supervisor:rw
            - ../dp-data/etc/supervisor:/etc/supervisor
        networks:
            - dp-internal
        labels:
            - "traefik.enable=false"

    dp-traefik:
        build: ./images/traefik
        container_name: dp-traefik
        restart: always
        image: dp-traefik
        ports:
            - "8080:8080"
            - "80:80"
            - "443:443"
        volumes:
            - ../dp-data/etc/traefik:/etc/traefik:rw
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - dp-internal
            - dp-proxy
        labels:
            - "traefik.enable=false"

    dp-workspace:
        build: ./images/workspace
        container_name: dp-workspace
        restart: always
        image: dp-workspace
        volumes:
            - ../dp-data/var/www:/var/www:rw
        networks:
            - dp-internal
        labels:
            - "traefik.enable=false"
